#!/bin/bash
string=$(ussdquery.py *102#)
balans=$(echo $string  | awk '{ print $2 }' | awk -F. '{ print $1 }') 
if expr $balans + 1 > /dev/null 2>&1
then
    if [ $balans -le 10 ]
    then
    credit=$(ussdquery.py *141#)
    run-standalone.sh dbus-send --type=method_call --dest=org.freedesktop.Notifications /org/freedesktop/Notifications org.freedesktop.Notifications.SystemNoteInfoprint string:"Будем брать кредит  $credit"
    sleep 18
    fi
    echo "$balans"
else
echo err
fi
run-standalone.sh dbus-send --type=method_call --dest=org.freedesktop.Notifications /org/freedesktop/Notifications org.freedesktop.Notifications.SystemNoteInfoprint string:"$string"